import * as THREE from 'three';
import metin1 from './assetsdata/metin1.js';
import metin2 from './assetsdata/metin2.js';
import metin3 from './assetsdata/metin3.js';
import metin4 from './assetsdata/metin4.js';
import turgut from './assetsdata/turgut.js';
import zeko from './assetsdata/zeko.js';
import nafi from './assetsdata/nafi.js';
import baki from './assetsdata/baki.js';
import p1 from './chunks/part1.js';
import p2 from './chunks/part2.js';
import p3 from './chunks/part3.js';
import p4 from './chunks/part4.js';
import p5 from './chunks/part5.js';
import p6 from './chunks/part6.js';
globalThis.MB_ASSET_PATHS={metin1:metin1,metin2:metin2,metin3:metin3,metin4:metin4,turgut:turgut,zeko:zeko,nafi:nafi,baki:baki};
const source=[p1,p2,p3,p4,p5,p6].join('');
eval(source);
